require: rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - db/migrate/**/*
    - db/**
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - config/**/*

Rails:
  Enabled: true

# checks for missing top-level documentation of classes and modules.
Documentation:
  Enabled: false

# Use nested module/class definitions instead of compact style.
ClassAndModuleChildren:
  Enabled: false

# Prefer `has_many :through` to `has_and_belongs_to_many`.
# HasAndBelongsToMany:
#   Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/NumericLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 300
  Exclude:
    - "test/**/*.rb"

Metrics/MethodLength:
  Max: 25

Naming/FileName:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "test/**/*.rb"
    - "spec/**/*.rb"
    - "db/seeds/**/*.rb"
    - "config/routes.rb"
    - "config/initializers/**/*.rb"
    - "spec/**/*"

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "Rakefile"
    - "**/*.rake"
    - "spec/**/*.rb"

Layout/EmptyLineAfterGuardClause:
  Enabled: false
# Rails/SkipsModelValidations:
#   Enabled: false

# Rails/HasManyOrHasOneDependent:
#   Enabled: false
