language: ruby
env:
  - DB=postgresql
before_script:
  - "cp config/database.travis.yml config/database.yml"
  - "psql -c 'create database mydb_test;' -U postgres"
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec
