development:
  adapter: postgresql
  encoding: utf8
  database: zelio_development
  username: postgres
  password:
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: zelio_test
  username: postgres
  password:
  host: localhost
  port: 5432
